"""Phase 1 standalone script generator.

Generates a self-contained, executable Python script from the finalized
RequestModel. Zero LLM dependency — can be committed, rerun, regression-tested.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any, Optional

from nagapasha.models.request_model import RequestModel


def _sanitize_constant(value: Any) -> str:
    """Sanitize a value for embedding as a Python constant."""
    if isinstance(value, bool):
        return "True" if value else "False"
    if isinstance(value, (int, float)):
        return repr(value)
    if value is None:
        return "None"
    if isinstance(value, dict):
        items = ", ".join(
            f"{_sanitize_constant(k)}: {_sanitize_constant(v)}"
            for k, v in sorted(value.items())
        )
        return f"{{{items}}}"
    if isinstance(value, list):
        items = ", ".join(_sanitize_constant(v) for v in value)
        return f"[{items}]"
    # String: escape and quote
    return repr(str(value))


class StaticScriptGenerator:
    """Generates a standalone, executable Python script."""

    def generate(
        self, request_model: RequestModel, output_path: Optional[Path] = None
    ) -> Path:
        """Generate a standalone Python script.

        Args:
            request_model: The finalized RequestModel with attack specs.
            output_path: Where to write the script. If None, writes to
                         scripts/engagements/<id>/run_payloads.py.

        Returns:
            Path to the generated script.
        """
        if output_path is None:
            eid = request_model.engagement_id or "unknown"
            output_path = (
                Path("scripts") / "engagements" / eid / "run_payloads.py"
            )
            output_path.parent.mkdir(parents=True, exist_ok=True)

        # Render the template
        rendered = self._render(request_model)
        output_path.write_text(rendered)
        return output_path

    def _render(self, req: RequestModel) -> str:
        """Render the script template using simple string replacement."""
        jwt_info = req.jwt_info or {}
        rate_config = req.rate_limit_config or {}
        baseline = req.baseline_fingerprint or {}

        # Encode values safely
        encoded_headers = _sanitize_constant(req.headers)
        encoded_cookies = _sanitize_constant(req.cookies)

        # Rate limit config
        burst = rate_config.get("burst", 10)
        refill_rate = rate_config.get("refill_rate", 4.0)

        # JWT info
        jwt_expires_at = jwt_info.get("exp")
        jwt_alg = jwt_info.get("alg")
        jwt_flagged = jwt_info.get("algorithm_flagged", False)

        # Attack specs
        attacks = req.attack_specs
        encoded_attacks = _sanitize_constant(attacks)

        # SSL verification default (scripts use SSL verification by default)
        verify_ssl = req.verify_ssl if hasattr(req, "verify_ssl") and req.verify_ssl else True

        result = _SCRIPT_TEMPLATE

        # Replace placeholders (order matters for nested replacements)
        result = result.replace("{{ENGAGEMENT_ID}}", req.engagement_id or "unknown")
        result = result.replace("{{GENERATED_DATE}}", "2026-08-10")
        result = result.replace("{{METHOD}}", _sanitize_constant(req.method))
        result = result.replace("{{URL}}", _sanitize_constant(req.url))
        result = result.replace("{{BASE_URL}}", _sanitize_constant(req.base_url))
        result = result.replace("{{HEADERS}}", encoded_headers)
        result = result.replace("{{COOKIES}}", encoded_cookies)
        result = result.replace("{{RATE_LIMIT_BURST}}", str(int(burst)))
        result = result.replace("{{RATE_LIMIT_RATE}}", str(refill_rate))
        result = result.replace("{{VERIFY_SSL}}", str(verify_ssl))
        result = result.replace("{{JWT_EXPIRES_AT}}", str(jwt_expires_at))
        result = result.replace("{{JWT_ALG}}", repr(jwt_alg))
        result = result.replace("{{JWT_FLAGGED}}", str(jwt_flagged))
        result = result.replace("{{BASELINE_STATUS}}",
                                _sanitize_constant(baseline.get("status_code")))
        result = result.replace("{{BASELINE_CONTENT_LENGTH}}",
                                _sanitize_constant(baseline.get("content_length")))
        result = result.replace("{{BASELINE_BODY_HASH}}",
                                _sanitize_constant(baseline.get("body_hash")))
        result = result.replace("{{BASELINE_AVG_TIME}}",
                                _sanitize_constant(baseline.get("avg_response_time")))
        result = result.replace("{{ATTACKS}}", encoded_attacks)

        return result


_SCRIPT_TEMPLATE = r'''#!/usr/bin/env python3
"""
Generated by nagapasha -- engagement {{ENGAGEMENT_ID}}
Generated on: {{GENERATED_DATE}}
This script is LLM-free. Rerun for regression testing.
"""

import asyncio
import httpx
import time
import json
import hashlib
import re
import urllib.parse
from dataclasses import dataclass
from typing import Optional, Any

# ---------------------------------------------------------------------------
# Configuration (from the planning stages)
# ---------------------------------------------------------------------------
BASE_URL = {{BASE_URL}}
METHOD = {{METHOD}}
HEADERS = {{HEADERS}}
COOKIES = {{COOKIES}}

# Rate limit: {{RATE_LIMIT_BURST}} burst, {{RATE_LIMIT_RATE}} req/s
RATE_LIMIT_BURST = {{RATE_LIMIT_BURST}}
RATE_LIMIT_RATE = {{RATE_LIMIT_RATE}}

# JWT watchdog
JWT_EXPIRES_AT = {{JWT_EXPIRES_AT}}  # unix timestamp
JWT_ALG = {{JWT_ALG}}
JWT_FLAGGED = {{JWT_FLAGGED}}

# Baseline fingerprint
BASELINE_STATUS = {{BASELINE_STATUS}}
BASELINE_CONTENT_LENGTH = {{BASELINE_CONTENT_LENGTH}}
BASELINE_BODY_HASH = {{BASELINE_BODY_HASH}}
BASELINE_AVG_TIME = {{BASELINE_AVG_TIME}}

# ---------------------------------------------------------------------------
# Payloads (from Strategist + Librarian + Fitter)
# ---------------------------------------------------------------------------
PAYLOADS = {{ATTACKS}}

# ---------------------------------------------------------------------------
# Core engine
# ---------------------------------------------------------------------------

class TokenBucket:
    """Token-bucket rate limiter."""

    def __init__(self, burst: int, refill_rate: float):
        self.burst = burst
        self.refill_rate = refill_rate
        self._tokens = float(burst)
        self._last = time.monotonic()

    def _refill(self):
        now = time.monotonic()
        elapsed = now - self._last
        self._last = now
        self._tokens = min(self.burst, self._tokens + elapsed * self.refill_rate)

    async def acquire(self):
        while True:
            self._refill()
            if self._tokens >= 1.0:
                self._tokens -= 1.0
                return
            wait = (1.0 - self._tokens) / self.refill_rate
            await asyncio.sleep(max(wait, 0.1))


@dataclass
class Delta:
    is_no_diff: bool = True
    status_delta: Optional[int] = None
    content_length_delta: int = 0
    response_time_delta: float = 0.0
    has_error: bool = False
    has_reflected: bool = False
    reflected_text: str = ""
    is_confirmed_hit: bool = False
    is_near_miss: bool = False


def compute_delta(status, body, elapsed):
    delta = Delta()

    # Status
    if status != BASELINE_STATUS:
        delta.status_delta = status - BASELINE_STATUS
        delta.is_no_diff = False

    # Content length
    cl_delta = len(body) - BASELINE_CONTENT_LENGTH
    if BASELINE_CONTENT_LENGTH > 0 and abs(cl_delta) / BASELINE_CONTENT_LENGTH > 0.10:
        delta.content_length_delta = cl_delta
        delta.is_no_diff = False

    # Response time
    if BASELINE_AVG_TIME > 0 and elapsed > BASELINE_AVG_TIME * 3:
        delta.response_time_delta = elapsed - BASELINE_AVG_TIME
        delta.is_no_diff = False

    # Error signatures
    error_sigs = [
        r"(?i)sql\s*(syntax|error|exception)",
        r"(?i)stack\s*trace",
        r"(?i)Traceback\s*\(",
        r"(?i)Fatal\s*error",
        r"(?i)permission\s*denied",
    ]
    for sig in error_sigs:
        if re.search(sig, body):
            delta.has_error = True
            delta.is_no_diff = False
            break

    # Reflected payload (checked in main loop)

    if delta.is_no_diff:
        return delta

    if delta.has_error:
        delta.is_confirmed_hit = True
    elif delta.status_delta is not None and delta.status_delta < 0:
        delta.is_near_miss = True
    elif delta.response_time_delta > 1.0:
        delta.is_near_miss = True

    return delta


async def main():
    limiter = TokenBucket(RATE_LIMIT_BURST, RATE_LIMIT_RATE)
    jwt_deadline = JWT_EXPIRES_AT

    print(f"=== nagapasha Phase 1 Runner ===")
    print(f"Target: {BASE_URL}")
    print(f"Method: {METHOD}")
    print(f"Rate limit: {RATE_LIMIT_BURST} burst / {RATE_LIMIT_RATE} req/s")
    if jwt_deadline:
        print(f"JWT expires at: {jwt_deadline} ({JWT_ALG})")
    print(f"Baseline: status={BASELINE_STATUS}, content-length={BASELINE_CONTENT_LENGTH}, "
          f"body-hash={BASELINE_BODY_HASH[:16]}...")
    print(f"Payloads: {sum(len(p.get('payloads', [])) for p in PAYLOADS)}")
    print("=" * 60)

    async with httpx.AsyncClient(verify={{VERIFY_SSL}}, timeout=30) as client:
        payload_num = 0
        for attack in PAYLOADS:
            param = attack.get("parameter", "unknown")
            placement = attack.get("placement", "full_replace")
            encoding = attack.get("encoding", "none")
            payloads = attack.get("payloads", [])

            for payload in payloads:
                payload_num += 1
                await limiter.acquire()

                # JWT watchdog
                if jwt_deadline and time.time() > jwt_deadline - 60:
                    print(f"\\nPAUSE: JWT expires soon (deadline={jwt_deadline})")
                    print("Get a new token and update the script, then rerun.")
                    break

                # Build the request
                constructed = build_request(
                    BASE_URL, METHOD, HEADERS, COOKIES,
                    param, placement, encoding,
                    attack.get("glue", ""),
                    payload,
                )

                resp = await client.request(METHOD, **constructed)
                delta = compute_delta(resp.status_code, resp.text, resp.elapsed)

                if delta.is_confirmed_hit:
                    print(
                        f"HIT #{payload_num}: [{param}] {payload[:30]}..."
                    )
                    if delta.reflected_text:
                        print(f"  reflected: {delta.reflected_text}")

                elif delta.is_near_miss:
                    print(
                        f"NEAR-MISS #{payload_num}: [{param}] {payload[:30]}..."
                        f" status_delta={delta.status_delta}"
                    )

                # else: no diff — silent


def build_request(base_url, method, headers, cookies,
                  param, placement, encoding, glue, payload):
    """Construct a request from a parameter, placement, and payload."""
    kwargs = {"headers": dict(headers), "cookies": dict(cookies)}

    if placement == "full_replace":
        # Replace the parameter value entirely
        if param and ("?" in base_url):
            new_url = _replace_query(base_url, param, payload)
        elif param and "/" in base_url:
            new_url = _replace_path(base_url, param, payload)
        else:
            new_url = base_url
        kwargs["url"] = new_url

    elif placement == "prefix":
        if param and ("?" in base_url):
            new_url = _prefix_query(base_url, param, glue, payload)
        else:
            new_url = base_url
        kwargs["url"] = new_url

    elif placement == "suffix":
        if param and ("?" in base_url):
            new_url = _suffix_query(base_url, param, glue, payload)
        else:
            new_url = base_url
        kwargs["url"] = new_url

    elif placement == "wrap":
        # Use glue as pre/post wrapper
        pre = glue.get("pre", "") if isinstance(glue, dict) else glue
        post = glue.get("post", "") if isinstance(glue, dict) else ""
        if isinstance(pre, str):
            pre = ""
        if isinstance(post, str):
            post = ""
        if param and ("?" in base_url):
            new_url = _wrap_query(base_url, param, pre, post, payload)
        else:
            new_url = base_url
        kwargs["url"] = new_url

    elif placement == "json_field_value":
        # Inject as a JSON field value — re-serialize the body
        kwargs["json"] = {param: payload}
        kwargs["headers"]["Content-Type"] = "application/json"

    elif placement == "header_value":
        # Inject as a header value
        kwargs["headers"][param] = payload
        kwargs["url"] = base_url

    else:
        kwargs["url"] = base_url

    return kwargs


def _replace_query(url, param, value):
    from urllib.parse import urlparse, parse_qs, urlencode, urlunparse
    parsed = urlparse(url)
    qs = parse_qs(parsed.query, keep_blank_values=True)
    qs[param] = [value]
    new_query = urlencode(qs, doseq=True)
    return urlunparse(parsed._replace(query=new_query))


def _replace_path(url, param, value):
    parts = url.split("/")
    for i, part in enumerate(parts):
        if part == param or (param and param in part):
            parts[i] = value
            break
    return "/".join(parts)


def _prefix_query(url, param, glue, value):
    from urllib.parse import urlparse, parse_qs, urlencode, urlunparse
    parsed = urlparse(url)
    qs = parse_qs(parsed.query, keep_blank_values=True)
    qs[param] = [glue + value]
    new_query = urlencode(qs, doseq=True)
    return urlunparse(parsed._replace(query=new_query))


def _suffix_query(url, param, glue, value):
    from urllib.parse import urlparse, parse_qs, urlencode, urlunparse
    parsed = urlparse(url)
    qs = parse_qs(parsed.query, keep_blank_values=True)
    qs[param] = [value + glue]
    new_query = urlencode(qs, doseq=True)
    return urlunparse(parsed._replace(query=new_query))


def _wrap_query(url, param, pre, post, value):
    from urllib.parse import urlparse, parse_qs, urlencode, urlunparse
    parsed = urlparse(url)
    qs = parse_qs(parsed.query, keep_blank_values=True)
    qs[param] = [pre + value + post]
    new_query = urlencode(qs, doseq=True)
    return urlunparse(parsed._replace(query=new_query))


if __name__ == "__main__":
    asyncio.run(main())
'''
