#!/usr/bin/env python3
"""
nagapasha Setup Script

Interactive setup that guides you through configuration and generates
the necessary .env and config files.
"""

import os
import sys
import getpass
from pathlib import Path

def print_banner():
    print("""
╔════════════════════════════════════════════════════════════╗
║           nagapasha — Adaptive AI-Powered Intruder         ║
║                    Interactive Setup Wizard                ║
╚════════════════════════════════════════════════════════════╝
    """)

def ask_question(question, default=None, secret=False):
    """Ask a question with optional default value."""
    if default:
        prompt = f"{question} [{default}]: "
    else:
        prompt = f"{question}: "

    if secret:
        answer = getpass.getpass(prompt)
    else:
        answer = input(prompt)

    if not answer and default:
        return default
    return answer

def setup_env_file():
    """Generate .env file with user-provided configuration."""
    print("\n📋 Configuration Setup")
    print("=" * 60)

    # Ask for API keys
    anthropic_key = ask_question(
        "Anthropic API Key",
        default="",
        secret=True
    )

    brave_key = ask_question(
        "Brave Search API Key (optional, for MCP web search)",
        default=""
    )

    # Ask for security configuration
    print("\n🔒 Security Configuration")
    print("-" * 60)

    hmac_key = ask_question(
        "HMAC Secret Key (leave empty to auto-generate)",
        default=""
    )

    if not hmac_key:
        import secrets
        hmac_key = secrets.token_hex(32)
        print(f"\n✅ Auto-generated HMAC key: {hmac_key}")

    # Ask for rate limiting
    print("\n⚡ Performance Configuration")
    print("-" * 60)

    rate_limit = ask_question(
        "Requests per second limit (default: 4)",
        default="4"
    )

    max_requests = ask_question(
        "Maximum total requests per run (default: 10000)",
        default="10000"
    )

    batch_size = ask_question(
        "Batch size for concurrent payload firing (default: 4)",
        default="4"
    )

    # Generate .env file
    print("\n💾 Generating .env file...")

    env_content = f"""# nagapasha Environment Configuration
# Generated by setup.py on {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

# Anthropic API Key (required for LLM agents)
ANTHROPIC_API_KEY={anthropic_key}

# Brave Search API Key (optional, for MCP web search)
BRAVE_API_KEY={brave_key}

# HMAC Secret Key (for request signing and engagement context)
HMAC_SECRET_KEY={hmac_key}

# Rate Limiting Configuration
RATE_LIMIT_PPS={rate_limit}
MAX_REQUESTS={max_requests}
BATCH_SIZE={batch_size}

# Enable/disable features
ENABLE_MCP_SEARCH={'true' if brave_key else 'false'}
LOG_LEVEL=INFO
"""

    env_path = Path(".env")
    env_path.write_text(env_content)
    print(f"✅ Created {env_path}")

    return env_path

def setup_readme():
    """Generate README.md if it doesn't exist or is outdated."""
    readme_path = Path("README.md")

    if not readme_path.exists():
        print("\n📖 Generating README.md...")
        readme_content = """# nagapasha — Adaptive AI-Powered Intruder

A multi-agent, self-scoping fuzzing tool that takes a single curl request and turns it into a targeted, rate-limit-aware, tech-stack-aware attack suite — without an LLM in the hot loop.

> **Disclaimer:** This tool is for authorized security testing only. Users are solely responsible for ensuring they have proper authorization before running scans against any target. The authors are not liable for misuse. Use at your own risk.

## Quick Start

```bash
# Install dependencies
pip install -e ".[dev]"

# Run setup (or manually create .env)
python setup.py

# Parse a curl command
nagapasha parse "curl -X GET 'https://example.com/api/users?page=1'"

# Run full pipeline
nagapasha full "curl -X GET 'https://example.com/api/users?page=1'"

# Run with dashboard
nagapasha dashboard --port 8000
```

## Features

- **Multi-Agent Pipeline**: Strategist, Librarian, Fitter, and Specialist agents
- **cURL Ingestion**: Parse any curl command into structured request model
- **Rate Limiting**: Token bucket rate limiter with 429 penalty
- **Tech Stack Awareness**: Detects frameworks and adapts testing strategy
- **Dashboard**: Live FastAPI dashboard with WebSocket updates
- **CI/CD Integration**: SARIF, JUnit XML, and HTML report formats
- **Authorization Gates**: Scope validation, kill switch, and engagement context
- **Evidence Integrity**: SHA256 hashing and PII redaction

## Documentation

See [docs/](docs/) for detailed documentation.

## License

MIT
"""
        readme_path.write_text(readme_content)
        print(f"✅ Created {readme_path}")

def setup_gitignore():
    """Generate .gitignore file."""
    gitignore_path = Path(".gitignore")

    if gitignore_path.exists():
        print("\n⚠️  .gitignore already exists. Skipping generation.")
        return

    print("\n🔒 Generating .gitignore...")

    gitignore_content = """# Python
__pycache__/
*.py[cod]
*$py.class
*.so
*.egg
*.egg-info/
dist/
build/
eggs/
.eggs/
*.whl

# Virtual environments
venv/
env/
ENV/
.venv

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# Environment
.env
.env.*
!.env.example

# Test results
test_results/
reports/
*.html
*.json
*.xml

# State files
*.state/
*.ctx
*.state.json

# Cache
.pytest_cache/
.hypothesis/
.mypy_cache/
.ruff_cache/

# Claude Code
.claude/
.agents/

# OS
.DS_Store
Thumbs.db

# Logs
*.log
logs/

# Temporary files
*.tmp
*.bak
*.swp
"""

    gitignore_path.write_text(gitignore_content)
    print(f"✅ Created {gitignore_path}")

def main():
    """Main setup function."""
    print_banner()

    print("Welcome to nagapasha setup!")
    print("This wizard will help you configure the tool.\n")

    # Generate .env file
    setup_env_file()

    # Generate .gitignore
    setup_gitignore()

    # Generate README if needed
    setup_readme()

    print("\n" + "=" * 60)
    print("✅ Setup complete!")
    print("\nNext steps:")
    print("1. Edit .env with your actual API keys")
    print("2. Install dependencies: pip install -e '.[dev]'")
    print("3. Run your first scan: nagapasha full \"curl ...\"")
    print("\nFor more information, see README.md")
    print("=" * 60)

if __name__ == "__main__":
    main()