#!/bin/bash
# nagapasha Interactive Setup Script
# This script guides you through the initial configuration

set -e

echo "╔════════════════════════════════════════════════════════════╗"
echo "║           nagapasha — Interactive Setup Wizard            ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Check if .env exists
if [ -f ".env" ]; then
    echo "⚠️  .env file already exists. Backing up to .env.backup"
    cp .env .env.backup
fi

# Generate random HMAC key
generate_hmac_key() {
    openssl rand -hex 32
}

# Ask for input with optional default
ask() {
    local prompt="$1"
    local default="${2:-}"
    local secret="${3:-0}"

    if [ -n "$default" ]; then
        prompt="$prompt [$default]: "
    else
        prompt="$prompt: "
    fi

    if [ "$secret" -eq 1 ]; then
        read -rsp "$prompt" answer
        echo ""
    else
        read -p "$prompt" answer
    fi

    if [ -z "$answer" ] && [ -n "$default" ]; then
        echo "$default"
    else
        echo "$answer"
    fi
}

echo "📋 Configuration Setup"
echo "═════════════════════════════════════════════════════════════"
echo ""

# Ask for API keys
ANTHROPIC_API_KEY=$(ask "Anthropic API Key" "" 1)
BRAVE_API_KEY=$(ask "Brave Search API Key (optional)" "")
HMAC_KEY=$(ask "HMAC Secret Key (leave empty to auto-generate)" "")

if [ -z "$HMAC_KEY" ]; then
    HMAC_KEY=$(generate_hmac_key)
    echo "✅ Auto-generated HMAC key: $HMAC_KEY"
fi

echo ""
echo "⚡ Performance Configuration"
echo "─────────────────────────────────────────────────────────────"

RATE_LIMIT=$(ask "Requests per second" "4")
MAX_REQUESTS=$(ask "Maximum requests per run" "10000")
BATCH_SIZE=$(ask "Batch size" "4")

echo ""
echo "💾 Generating .env file..."

cat > .env << EOF
# nagapasha Environment Configuration
# Generated by setup.sh on $(date)

# Anthropic API Key (required for LLM agents)
ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY

# Brave Search API Key (optional, for MCP web search)
BRAVE_API_KEY=$BRAVE_API_KEY

# HMAC Secret Key (for request signing and engagement context)
HMAC_SECRET_KEY=$HMAC_KEY

# Rate Limiting Configuration
RATE_LIMIT_PPS=$RATE_LIMIT
MAX_REQUESTS=$MAX_REQUESTS
BATCH_SIZE=$BATCH_SIZE

# Enable/disable features
ENABLE_MCP_SEARCH=$([ -n "$BRAVE_API_KEY" ] && echo "true" || echo "false")
LOG_LEVEL=INFO
EOF

echo "✅ Created .env"

echo ""
echo "🔒 Generating .gitignore..."

cat > .gitignore << 'EOF'
# Python
__pycache__/
*.py[cod]
*$py.class
*.so
*.egg
*.egg-info/
dist/
build/
eggs/
.eggs/
*.whl

# Virtual environments
venv/
env/
ENV/
.venv

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# Environment
.env
.env.*
!.env.example

# Test results
test_results/
reports/
test-*.ctx
*.state.json

# State files
*.state/
*.ctx

# Documentation (plans and drafts, keep README.md)
docs/
*.md
!README.md

# Cache
.pytest_cache/
.hypothesis/
.mypy_cache/
.ruff_cache/

# Claude Code
.claude/
.agents/

# OS
.DS_Store
Thumbs.db

# Logs
*.log
logs/

# Temporary files
*.tmp
*.bak
*.swp
EOF

echo "✅ Created .gitignore"

echo ""
echo "═════════════════════════════════════════════════════════════"
echo "✅ Setup complete!"
echo ""
echo "Next steps:"
echo "1. Edit .env with your actual API keys"
echo "2. Install dependencies: pip install -e '.[dev]'"
echo "3. Run your first scan: nagapasha full \"curl ...\""
echo ""
echo "For more information, see README.md"
echo "═════════════════════════════════════════════════════════════"