#!/usr/bin/env python3
"""
Generated by nagapasha -- engagement unknown
Generated on: 2026-08-10
This script is LLM-free. Rerun for regression testing.
"""

import asyncio
import httpx
import time
import json
import hashlib
import re
import urllib.parse
from dataclasses import dataclass
from typing import Optional, Any

# ---------------------------------------------------------------------------
# Configuration (from the planning stages)
# ---------------------------------------------------------------------------
BASE_URL = 'https://preview.owasp-juice.shop'
METHOD = 'GET'
HEADERS = {'Accept': 'application/json, text/plain, */*', 'Accept-Encoding': 'gzip, deflate, br', 'Accept-Language': 'en-GB,en;q=0.9', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJkYXRhIjp7ImlkIjoxLCJ1c2VybmFtZSI6IiIsImVtYWlsIjoiYWRtaW5AanVpY2Utc2gub3AiLCJwYXNzd29yZCI6IjAxOTIwMjNhN2JiZDczMjUwNTE2ZjA2OWRmMThiNTAwIiwicm9sZSI6ImFkbWluIiwiZGVsdXhlVG9rZW4iOiIiLCJsYXN0TG9naW5JcCI6IjIwMy4wLjExMy40MiIsInByb2ZpbGVJbWFnZSI6ImFzc2V0cy9wdWJsaWMvaW1hZ2VzL3VwbG9hZHMvZGVmYXVsdEFkbWluLnBuZyIsInRvdHBTZWNyZXQiOiIiLCJpc0FjdGl2ZSI6dHJ1ZSwiY3JlYXRlZEF0IjoiMjAyNi0wOC0yNSAwMzoyNjo1Ny44NzggKzAwOjAwIiwidXBkYXRlZEF0IjoiMjAyNi0wOC0yNSAwNDowMTo1Ni4zMzYgKzAwOjAwIiwiZGVsZXRlZEF0IjpudWxsfSwiYmlkIjoxLCJpYXQiOjE3ODc2MzYwNjF9.iAUon_O5ap0SkjwwG-DwYFr3Kqb_7BBlMqlZcQde2w4lPVJGZf_3fqAGWvyk-7c8sTcK50KZpvOxQwbcy0qsThnJ7gC2AaHZuj1GT-etNRpfgguLi1qcfm48UsI5iTD8AkdEdpVxXDpKLfOC9QhpUYbpM5ggE9u0KzSRaB5u1eE', 'Host': 'preview.owasp-juice.shop', 'Priority': 'u=1, i', 'Referer': 'https://preview.owasp-juice.shop/', 'Sec-Ch-Ua': '"Not;A=Brand";v="8", "Chromium";v="150"', 'Sec-Ch-Ua-Mobile': '?0', 'Sec-Ch-Ua-Platform': '"Linux"', 'Sec-Fetch-Dest': 'empty', 'Sec-Fetch-Mode': 'cors', 'Sec-Fetch-Site': 'same-origin', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36'}
COOKIES = {'cookieconsent_status': 'dismiss', 'language': 'en', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJkYXRhIjp7ImlkIjoxLCJ1c2VybmFtZSI6IiIsImVtYWlsIjoiYWRtaW5AanVpY2Utc2gub3AiLCJwYXNzd29yZCI6IjAxOTIwMjNhN2JiZDczMjUwNTE2ZjA2OWRmMThiNTAwIiwicm9sZSI6ImFkbWluIiwiZGVsdXhlVG9rZW4iOiIiLCJsYXN0TG9naW5JcCI6IjIwMy4wLjExMy40MiIsInByb2ZpbGVJbWFnZSI6ImFzc2V0cy9wdWJsaWMvaW1hZ2VzL3VwbG9hZHMvZGVmYXVsdEFkbWluLnBuZyIsInRvdHBTZWNyZXQiOiIiLCJpc0FjdGl2ZSI6dHJ1ZSwiY3JlYXRlZEF0IjoiMjAyNi0wOC0yNSAwMzoyNjo1Ny44NzggKzAwOjAwIiwidXBkYXRlZEF0IjoiMjAyNi0wOC0yNSAwNDowMTo1Ni4zMzYgKzAwOjAwIiwiZGVsZXRlZEF0IjpudWxsfSwiYmlkIjoxLCJpYXQiOjE3ODc2MzYwNjF9.iAUon_O5ap0SkjwwG-DwYFr3Kqb_7BBlMqlZcQde2w4lPVJGZf_3fqAGWvyk-7c8sTcK50KZpvOxQwbcy0qsThnJ7gC2AaHZuj1GT-etNRpfgguLi1qcfm48UsI5iTD8AkdEdpVxXDpKLfOC9QhpUYbpM5ggE9u0KzSRaB5u1eE', 'welcomebanner_status': 'dismiss'}

# Rate limit: 10 burst, 4.0 req/s
RATE_LIMIT_BURST = 10
RATE_LIMIT_RATE = 4.0

# JWT watchdog
JWT_EXPIRES_AT = None  # unix timestamp
JWT_ALG = None
JWT_FLAGGED = False

# Baseline fingerprint
BASELINE_STATUS = None
BASELINE_CONTENT_LENGTH = None
BASELINE_BODY_HASH = None
BASELINE_AVG_TIME = None

# ---------------------------------------------------------------------------
# Payloads (from Strategist + Librarian + Fitter)
# ---------------------------------------------------------------------------
PAYLOADS = []

# ---------------------------------------------------------------------------
# Core engine
# ---------------------------------------------------------------------------

class TokenBucket:
    """Token-bucket rate limiter."""

    def __init__(self, burst: int, refill_rate: float):
        self.burst = burst
        self.refill_rate = refill_rate
        self._tokens = float(burst)
        self._last = time.monotonic()

    def _refill(self):
        now = time.monotonic()
        elapsed = now - self._last
        self._last = now
        self._tokens = min(self.burst, self._tokens + elapsed * self.refill_rate)

    async def acquire(self):
        while True:
            self._refill()
            if self._tokens >= 1.0:
                self._tokens -= 1.0
                return
            wait = (1.0 - self._tokens) / self.refill_rate
            await asyncio.sleep(max(wait, 0.1))


@dataclass
class Delta:
    is_no_diff: bool = True
    status_delta: Optional[int] = None
    content_length_delta: int = 0
    response_time_delta: float = 0.0
    has_error: bool = False
    has_reflected: bool = False
    reflected_text: str = ""
    is_confirmed_hit: bool = False
    is_near_miss: bool = False


def compute_delta(status, body, elapsed):
    delta = Delta()

    # Status
    if status != BASELINE_STATUS:
        delta.status_delta = status - BASELINE_STATUS
        delta.is_no_diff = False

    # Content length
    cl_delta = len(body) - BASELINE_CONTENT_LENGTH
    if BASELINE_CONTENT_LENGTH > 0 and abs(cl_delta) / BASELINE_CONTENT_LENGTH > 0.10:
        delta.content_length_delta = cl_delta
        delta.is_no_diff = False

    # Response time
    if BASELINE_AVG_TIME > 0 and elapsed > BASELINE_AVG_TIME * 3:
        delta.response_time_delta = elapsed - BASELINE_AVG_TIME
        delta.is_no_diff = False

    # Error signatures
    error_sigs = [
        r"(?i)sql\s*(syntax|error|exception)",
        r"(?i)stack\s*trace",
        r"(?i)Traceback\s*\(",
        r"(?i)Fatal\s*error",
        r"(?i)permission\s*denied",
    ]
    for sig in error_sigs:
        if re.search(sig, body):
            delta.has_error = True
            delta.is_no_diff = False
            break

    # Reflected payload (checked in main loop)

    if delta.is_no_diff:
        return delta

    if delta.has_error:
        delta.is_confirmed_hit = True
    elif delta.status_delta is not None and delta.status_delta < 0:
        delta.is_near_miss = True
    elif delta.response_time_delta > 1.0:
        delta.is_near_miss = True

    return delta


async def main():
    limiter = TokenBucket(RATE_LIMIT_BURST, RATE_LIMIT_RATE)
    jwt_deadline = JWT_EXPIRES_AT

    print(f"=== nagapasha Phase 1 Runner ===")
    print(f"Target: {BASE_URL}")
    print(f"Method: {METHOD}")
    print(f"Rate limit: {RATE_LIMIT_BURST} burst / {RATE_LIMIT_RATE} req/s")
    if jwt_deadline:
        print(f"JWT expires at: {jwt_deadline} ({JWT_ALG})")
    print(f"Baseline: status={BASELINE_STATUS}, content-length={BASELINE_CONTENT_LENGTH}, "
          f"body-hash={BASELINE_BODY_HASH[:16]}...")
    print(f"Payloads: {sum(len(p.get('payloads', [])) for p in PAYLOADS)}")
    print("=" * 60)

    async with httpx.AsyncClient(verify=True, timeout=30) as client:
        payload_num = 0
        for attack in PAYLOADS:
            param = attack.get("parameter", "unknown")
            placement = attack.get("placement", "full_replace")
            encoding = attack.get("encoding", "none")
            payloads = attack.get("payloads", [])

            for payload in payloads:
                payload_num += 1
                await limiter.acquire()

                # JWT watchdog
                if jwt_deadline and time.time() > jwt_deadline - 60:
                    print(f"\\nPAUSE: JWT expires soon (deadline={jwt_deadline})")
                    print("Get a new token and update the script, then rerun.")
                    break

                # Build the request
                constructed = build_request(
                    BASE_URL, METHOD, HEADERS, COOKIES,
                    param, placement, encoding,
                    attack.get("glue", ""),
                    payload,
                )

                resp = await client.request(METHOD, **constructed)
                delta = compute_delta(resp.status_code, resp.text, resp.elapsed)

                if delta.is_confirmed_hit:
                    print(
                        f"HIT #{payload_num}: [{param}] {payload[:30]}..."
                    )
                    if delta.reflected_text:
                        print(f"  reflected: {delta.reflected_text}")

                elif delta.is_near_miss:
                    print(
                        f"NEAR-MISS #{payload_num}: [{param}] {payload[:30]}..."
                        f" status_delta={delta.status_delta}"
                    )

                # else: no diff — silent


def build_request(base_url, method, headers, cookies,
                  param, placement, encoding, glue, payload):
    """Construct a request from a parameter, placement, and payload."""
    kwargs = {"headers": dict(headers), "cookies": dict(cookies)}

    if placement == "full_replace":
        # Replace the parameter value entirely
        if param and ("?" in base_url):
            new_url = _replace_query(base_url, param, payload)
        elif param and "/" in base_url:
            new_url = _replace_path(base_url, param, payload)
        else:
            new_url = base_url
        kwargs["url"] = new_url

    elif placement == "prefix":
        if param and ("?" in base_url):
            new_url = _prefix_query(base_url, param, glue, payload)
        else:
            new_url = base_url
        kwargs["url"] = new_url

    elif placement == "suffix":
        if param and ("?" in base_url):
            new_url = _suffix_query(base_url, param, glue, payload)
        else:
            new_url = base_url
        kwargs["url"] = new_url

    elif placement == "wrap":
        # Use glue as pre/post wrapper
        pre = glue.get("pre", "") if isinstance(glue, dict) else glue
        post = glue.get("post", "") if isinstance(glue, dict) else ""
        if isinstance(pre, str):
            pre = ""
        if isinstance(post, str):
            post = ""
        if param and ("?" in base_url):
            new_url = _wrap_query(base_url, param, pre, post, payload)
        else:
            new_url = base_url
        kwargs["url"] = new_url

    elif placement == "json_field_value":
        # Inject as a JSON field value — re-serialize the body
        kwargs["json"] = {param: payload}
        kwargs["headers"]["Content-Type"] = "application/json"

    elif placement == "header_value":
        # Inject as a header value
        kwargs["headers"][param] = payload
        kwargs["url"] = base_url

    else:
        kwargs["url"] = base_url

    return kwargs


def _replace_query(url, param, value):
    from urllib.parse import urlparse, parse_qs, urlencode, urlunparse
    parsed = urlparse(url)
    qs = parse_qs(parsed.query, keep_blank_values=True)
    qs[param] = [value]
    new_query = urlencode(qs, doseq=True)
    return urlunparse(parsed._replace(query=new_query))


def _replace_path(url, param, value):
    parts = url.split("/")
    for i, part in enumerate(parts):
        if part == param or (param and param in part):
            parts[i] = value
            break
    return "/".join(parts)


def _prefix_query(url, param, glue, value):
    from urllib.parse import urlparse, parse_qs, urlencode, urlunparse
    parsed = urlparse(url)
    qs = parse_qs(parsed.query, keep_blank_values=True)
    qs[param] = [glue + value]
    new_query = urlencode(qs, doseq=True)
    return urlunparse(parsed._replace(query=new_query))


def _suffix_query(url, param, glue, value):
    from urllib.parse import urlparse, parse_qs, urlencode, urlunparse
    parsed = urlparse(url)
    qs = parse_qs(parsed.query, keep_blank_values=True)
    qs[param] = [value + glue]
    new_query = urlencode(qs, doseq=True)
    return urlunparse(parsed._replace(query=new_query))


def _wrap_query(url, param, pre, post, value):
    from urllib.parse import urlparse, parse_qs, urlencode, urlunparse
    parsed = urlparse(url)
    qs = parse_qs(parsed.query, keep_blank_values=True)
    qs[param] = [pre + value + post]
    new_query = urlencode(qs, doseq=True)
    return urlunparse(parsed._replace(query=new_query))


if __name__ == "__main__":
    asyncio.run(main())
